// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RichCluster
Rcpp::List RichCluster(std::string distanceMetric, double distanceCutoff, std::string mergeStrategy, double membershipCutoff, Rcpp::CharacterVector termNameColumn, Rcpp::CharacterVector geneIDColumn, Rcpp::NumericVector PvalueColumn);
RcppExport SEXP _RichCluster_RichCluster(SEXP distanceMetricSEXP, SEXP distanceCutoffSEXP, SEXP mergeStrategySEXP, SEXP membershipCutoffSEXP, SEXP termNameColumnSEXP, SEXP geneIDColumnSEXP, SEXP PvalueColumnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type distanceMetric(distanceMetricSEXP);
    Rcpp::traits::input_parameter< double >::type distanceCutoff(distanceCutoffSEXP);
    Rcpp::traits::input_parameter< std::string >::type mergeStrategy(mergeStrategySEXP);
    Rcpp::traits::input_parameter< double >::type membershipCutoff(membershipCutoffSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type termNameColumn(termNameColumnSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type geneIDColumn(geneIDColumnSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type PvalueColumn(PvalueColumnSEXP);
    rcpp_result_gen = Rcpp::wrap(RichCluster(distanceMetric, distanceCutoff, mergeStrategy, membershipCutoff, termNameColumn, geneIDColumn, PvalueColumn));
    return rcpp_result_gen;
END_RCPP
}
// ComputeDistanceMatrix
Rcpp::NumericMatrix ComputeDistanceMatrix(std::string distanceMetric, double distanceCutoff, Rcpp::CharacterVector termNameColumn, Rcpp::CharacterVector geneIDColumn, Rcpp::NumericVector PvalueColumn);
RcppExport SEXP _RichCluster_ComputeDistanceMatrix(SEXP distanceMetricSEXP, SEXP distanceCutoffSEXP, SEXP termNameColumnSEXP, SEXP geneIDColumnSEXP, SEXP PvalueColumnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type distanceMetric(distanceMetricSEXP);
    Rcpp::traits::input_parameter< double >::type distanceCutoff(distanceCutoffSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type termNameColumn(termNameColumnSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type geneIDColumn(geneIDColumnSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type PvalueColumn(PvalueColumnSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeDistanceMatrix(distanceMetric, distanceCutoff, termNameColumn, geneIDColumn, PvalueColumn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RichCluster_RichCluster", (DL_FUNC) &_RichCluster_RichCluster, 7},
    {"_RichCluster_ComputeDistanceMatrix", (DL_FUNC) &_RichCluster_ComputeDistanceMatrix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RichCluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
