# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runDavidClustering <- function(terms, geneIDs, similarityThreshold, initialGroupMembership, finalGroupMembership, multipleLinkageThreshold) {
    .Call(`_richCluster_runDavidClustering`, terms, geneIDs, similarityThreshold, initialGroupMembership, finalGroupMembership, multipleLinkageThreshold)
}

runRichCluster <- function(terms, geneIDs, distanceMetric, distanceCutoff, linkageMethod, linkageCutoff) {
    .Call(`_richCluster_runRichCluster`, terms, geneIDs, distanceMetric, distanceCutoff, linkageMethod, linkageCutoff)
}

