# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name RichCluster
#' @export
NULL

RunRichCluster <- function(distanceMetric, distanceCutoff, linkageMethod, linkageCutoff, termNameColumn, geneIDColumn) {
    .Call(`_RichCluster_RunRichCluster`, distanceMetric, distanceCutoff, linkageMethod, linkageCutoff, termNameColumn, geneIDColumn)
}

#' @name ComputeDistanceMatrix
#' @export
ComputeDistanceMatrix <- function(distanceMetric, distanceCutoff, termNameColumn, geneIDColumn, PvalueColumn) {
    .Call(`_RichCluster_ComputeDistanceMatrix`, distanceMetric, distanceCutoff, termNameColumn, geneIDColumn, PvalueColumn)
}

